version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-12-12T19-27-27Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    - "MINIO_ROOT_USER=minioadmin"
    - "MINIO_ROOT_PASSWORD=minioadmin"
    - "MINIO_API_SELECT_PARQUET=on"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  createbuckets:
    image: minio/mc
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio1:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/warehouse;
      exit 0;
      "

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  #  postgres:
  #    image: postgres:13.4-bullseye
  #    hostname: postgres
  #    ports:
  #      - 5432:5432
  #    environment:
  #      - POSTGRES_USER=admin
  #      - POSTGRES_PASSWORD=password
  #      - POSTGRES_DB=demo_catalog
  #    healthcheck:
  #      test: [ "CMD-SHELL", "pg_isready" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5
  #    networks:
  #      - db

  mysql:
    restart: always
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=demo_catalog"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
    command:
      - "mysqld"
      - "--innodb_buffer_pool_size=1024M"
      - "--max-connections=100000"

## By default, this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

networks:
  db: